insert into chapters (id, bookId, chapter, title) values(1, 1, 1, "The verb ‘to be’ | Czasownik ‘być’");
insert into chapters (id, bookId, chapter, title) values(2, 1, 2, "This and That | To i Tamto");
insert into chapters (id, bookId, chapter, title) values(3, 1, 3, "Plural Nouns | Rzeczowniki w Liczbie Mnogiej");
insert into chapters (id, bookId, chapter, title) values(4, 1, 4, "These, Those | Te i Tamte");
insert into chapters (id, bookId, chapter, title) values(5, 1, 5, "Possessive Adjectives and Pronouns | Zaimki Dzierżawcze");
insert into chapters (id, bookId, chapter, title) values(6, 1, 6, "Days, Months & Time | Dni, Miesiące i Czas");
insert into chapters (id, bookId, chapter, title) values(7, 1, 7, "Questions | Pytania");
insert into chapters (id, bookId, chapter, title) values(8, 1, 8, "Prepositions of place | Przyimki Miejsca");
insert into chapters (id, bookId, chapter, title) values(9, 1, 9, "There is/There are | Jest/Są");
insert into chapters (id, bookId, chapter, title) values(10, 1, 10, "Present Simple | Czas Teraźniejszy Prosty");
insert into chapters (id, bookId, chapter, title) values(11, 1, 11, "Have, Like, Want | Mieć, Lubić, Chcieć");
insert into chapters (id, bookId, chapter, title) values(12, 1, 12, "Object Pronouns | Zaimki Dopełnieniowe");
insert into chapters (id, bookId, chapter, title) values(13, 1, 13, "Frequency Adverbs | Przysłówki Wyrażające Częstotliwość");
insert into chapters (id, bookId, chapter, title) values(14, 1, 14, "Imperatives | Tryb Rozkazujący");
insert into chapters (id, bookId, chapter, title) values(15, 1, 15, "Saxon Genitive | Dopełniacz Saksoński");
insert into chapters (id, bookId, chapter, title) values(16, 1, 16, "Present Continuous | Czas Teraźniejszy Ciągły");
insert into chapters (id, bookId, chapter, title) values(17, 1, 17, "Countable & Uncountable Nouns | Rzeczowniki Policzalne i Niepoliczalne");
insert into chapters (id, bookId, chapter, title) values(18, 1, 18, "Can | Móc/Umieć/Potrafić");
insert into chapters (id, bookId, chapter, title) values(19, 1, 19, "Must & Have to | Musieć");
insert into chapters (id, bookId, chapter, title) values(20, 1, 20, "Comparative Adjectives | Stopień Wyższy Przymiotnika");
insert into chapters (id, bookId, chapter, title) values(21, 1, 21, "Adverbs | Przysłówki");
insert into chapters (id, bookId, chapter, title) values(22, 1, 22, "Reflexive Pronouns | Zaimki Zwrotne");
insert into chapters (id, bookId, chapter, title) values(23, 1, 23, "To be Going to do something | Wyrażenie Zamiaru");
insert into chapters (id, bookId, chapter, title) values(24, 1, 24, "Negative Questions | Pytania Przeczące");
insert into chapters (id, bookId, chapter, title) values(25, 1, 25, "Gerund and Infinitive | Czasownik z końcówką -ing oraz Bezokolicznik");
insert into chapters (id, bookId, chapter, title) values(26, 1, 26, "Prepositions 1 | Przyimki, część 1");
insert into chapters (id, bookId, chapter, title) values(27, 1, 27, "Expressions 1 | Wyrażenia, część 1");
insert into chapters (id, bookId, chapter, title) values(28, 1, 28, "Review - Sprawdź się!");
insert into chapters (id, bookId, chapter, title) values(29, 2, 1, "Present Tenses - Review | Czasy Teraźniejsze - Powtórka");
insert into chapters (id, bookId, chapter, title) values(30, 2, 2, "Pronouns & Saxon Genitive | Zaimki oraz Dopełniacz Saksoński");
insert into chapters (id, bookId, chapter, title) values(31, 2, 3, "Much, Many, Few, Little | Dużo, Mało");
insert into chapters (id, bookId, chapter, title) values(32, 2, 4, "Noun Comparison | Porównywanie Rzeczowników");
insert into chapters (id, bookId, chapter, title) values(33, 2, 5, "Will - Future Tense | Czas Przyszły");
insert into chapters (id, bookId, chapter, title) values(34, 2, 6, "Past simple - Verb ‘to be’ | Czasownik ‘być’ w Czasie Przeszłym");
insert into chapters (id, bookId, chapter, title) values(35, 2, 7, "Past Simple - Regular Verbs | Czasowniki Regularne w Czasie Przeszłym");
insert into chapters (id, bookId, chapter, title) values(36, 2, 8, "8 Past Simple Irregular Verbs 1 | Czasowniki Nieregularne, część 1");
insert into chapters (id, bookId, chapter, title) values(37, 2, 9, "Past Simple - Irregular Verbs 2 | Czasowniki Nieregularne, część 2");
insert into chapters (id, bookId, chapter, title) values(38, 2, 10, "Past Continuous | Czas Przeszły Ciągły");
insert into chapters (id, bookId, chapter, title) values(39, 2, 11, "‘Have to’ in three tenses | ‘Have to’ w trzech czasach");
insert into chapters (id, bookId, chapter, title) values(40, 2, 12, "Can, Could & To be able | ‘Can’ w Czasie Teraźniejszym, Przeszłym i Przyszłym");
insert into chapters (id, bookId, chapter, title) values(41, 2, 13, "Comparatives & Superlatives | Stopień Wyższy i Najwyższy Przymiotnika");
insert into chapters (id, bookId, chapter, title) values(42, 2, 14, "The First Conditional | Pierwszy Tryb Warunkowy");
insert into chapters (id, bookId, chapter, title) values(43, 2, 15, "Anything, Something, Nothing | Coś i Nic");
insert into chapters (id, bookId, chapter, title) values(44, 2, 16, "Will & Going to | Czas Przyszły oraz Wyrażenie Going to");
insert into chapters (id, bookId, chapter, title) values(45, 2, 17, "Would like | Chciałbym/Chciałabym");
insert into chapters (id, bookId, chapter, title) values(46, 2, 18, "Should | Powinność");
insert into chapters (id, bookId, chapter, title) values(47, 2, 19, "Too & Enough | Za i Zbyt");
insert into chapters (id, bookId, chapter, title) values(48, 2, 20, "Still, Yet, Already, Not Anymore | Wciąż, Jeszcze, Już i Już Nie");
insert into chapters (id, bookId, chapter, title) values(49, 2, 21, "‘There’ in three tenses | Forma ‘There’ w trzech czasach");
insert into chapters (id, bookId, chapter, title) values(50, 2, 22, "Adjectives with -ing & -ed ending | Przymiotniki z końcówką -ing & -ed");
insert into chapters (id, bookId, chapter, title) values(51, 2, 23, "It’s Necessary/Important to ... | Trzeba, Ważne jest....");
insert into chapters (id, bookId, chapter, title) values(52, 2, 24, "Prepositions 2 | Przyimki, część 2");
insert into chapters (id, bookId, chapter, title) values(53, 2, 25, "Prepositions in Questions | Przyimki w Pytaniach");
insert into chapters (id, bookId, chapter, title) values(54, 2, 26, "Expressions 2 | Wyrażenia, część 2");
insert into chapters (id, bookId, chapter, title) values(55, 2, 27, "Short Answers | Krótkie Odpowiedzi");
insert into chapters (id, bookId, chapter, title) values(56, 2, 28, "Review - Sprawdź Się!");
insert into chapters (id, bookId, chapter, title) values(57, 3, 1, "Tenses Review | Powtórka Czasów");
insert into chapters (id, bookId, chapter, title) values(58, 3, 2, "Past Simple vs. Past Continuous | Czas Przeszły Prosty kontra Ciągły");
insert into chapters (id, bookId, chapter, title) values(59, 3, 3, "Nouns, Comparison, As...As | Rzeczowniki, Porównywanie, Tyle...Ile; Tak...Jak");
insert into chapters (id, bookId, chapter, title) values(60, 3, 4, "Present Perfect | Czas Teraźniejszy Dokonany");
insert into chapters (id, bookId, chapter, title) values(61, 3, 5, "Present Perfect - ever, never | Czas Present Perfect z Kiedykolwiek, Nigdy");
insert into chapters (id, bookId, chapter, title) values(62, 3, 6, "Present Perfect - Already, Yet, Just | Present Perfect z Już, Jeszcze, Właśnie");
insert into chapters (id, bookId, chapter, title) values(63, 3, 7, "Present Perfect - For & Since | Present Perfect w użyciu z Przez, Od i Odkąd");
insert into chapters (id, bookId, chapter, title) values(64, 3, 8, "Present Perfect Continuous | Czas Present Perfect Ciągły");
insert into chapters (id, bookId, chapter, title) values(65, 3, 9, "Present Perfect vs. Present Perfect Continuous | Czas Teraźniejszy Dokonany kontra Ciągły");
insert into chapters (id, bookId, chapter, title) values(66, 3, 10, "Irregular Verbs - Third Form | Czasowniki Nieregularne - Trzecia Forma");
insert into chapters (id, bookId, chapter, title) values(67, 3, 11, "Indirect Questions 1 | Pytania Zależne, część 1");
insert into chapters (id, bookId, chapter, title) values(68, 3, 12, "Modal Verbs | Czasowniki Modalne");
insert into chapters (id, bookId, chapter, title) values(69, 3, 13, "Someone, Anyone, No one, etc. | Ktoś, Nikt, etc");
insert into chapters (id, bookId, chapter, title) values(70, 3, 14, "It takes... 1 | To zabiera/zajmuje..., część 1");
insert into chapters (id, bookId, chapter, title) values(71, 3, 15, "Used to | Przeszłe Zwyczaje");
insert into chapters (id, bookId, chapter, title) values(72, 3, 16, "Want Somebody To Do Something | Chcieć, żeby Ktoś Coś Zrobił");
insert into chapters (id, bookId, chapter, title) values(73, 3, 17, "Indirect Imperatives | Rozkazy Pośrednie");
insert into chapters (id, bookId, chapter, title) values(74, 3, 18, "Make & Do 1 | Tworzyć i Robić, część 1");
insert into chapters (id, bookId, chapter, title) values(75, 3, 19, "Future Simple/Future Continuous | Czas Przyszły Prosty/Ciągły");
insert into chapters (id, bookId, chapter, title) values(76, 3, 20, "First Conditional + Time Clauses | Pierwszy Tryb Warunkowy+Zdania Czasowe");
insert into chapters (id, bookId, chapter, title) values(77, 3, 21, "Second Conditional | Drugi Tryb Warunkowy");
insert into chapters (id, bookId, chapter, title) values(78, 3, 22, "Get - Expressions | Zwroty z czasownikiem Get");
insert into chapters (id, bookId, chapter, title) values(79, 3, 23, "All, None, Both, Neither, Either... | Wszyscy, Obydwoje, Nikt, Żaden....");
insert into chapters (id, bookId, chapter, title) values(80, 3, 24, "Make Somebody Do Something | Sprawić, aby Ktoś Coś Zrobił");
insert into chapters (id, bookId, chapter, title) values(81, 3, 25, "Questions about Subjects & Objects | Pytania o Podmiot i Dopełnienie");
insert into chapters (id, bookId, chapter, title) values(82, 3, 26, "Prepositions 3 | Przyimki, część 3");
insert into chapters (id, bookId, chapter, title) values(83, 3, 27, "Expressions 3 | Wyrażenia, część 3");
insert into chapters (id, bookId, chapter, title) values(84, 3, 28, "Review - Sprawdź Się!");
insert into chapters (id, bookId, chapter, title) values(85, 4, 1, "UTenses Review | Powtórka Czasów");
insert into chapters (id, bookId, chapter, title) values(86, 4, 2, "Present Perfect vs. Past Simple | Czas Teraźniejszy Dokonany/Przeszły Prosty");
insert into chapters (id, bookId, chapter, title) values(87, 4, 3, "Irregular Verbs | Czasowniki Nieregularne");
insert into chapters (id, bookId, chapter, title) values(88, 4, 4, "There in All Tenses | There we Wszystkich Czasach");
insert into chapters (id, bookId, chapter, title) values(89, 4, 5, "Passive Voice 1 | Strona Bierna, część 1");
insert into chapters (id, bookId, chapter, title) values(90, 4, 6, "Other, Another, Others | Inni, Inny, Inne...");
insert into chapters (id, bookId, chapter, title) values(91, 4, 7, "Make & Do 2 | Tworzyć i Robić, część 2");
insert into chapters (id, bookId, chapter, title) values(92, 4, 8, "Say & Tell | Mówić i Powiedzieć");
insert into chapters (id, bookId, chapter, title) values(93, 4, 9, "Gerund & Infinitive 1 | Czasownik z końcówką -ing & Bezokolicznik, część 1");
insert into chapters (id, bookId, chapter, title) values(94, 4, 10, "Bare Infinitive 1 | Nagi Bezokolicznik, część 1");
insert into chapters (id, bookId, chapter, title) values(95, 4, 11, "Indirect Imperatives & Requests | Rozkazy i Prośby w Mowie Zależnej");
insert into chapters (id, bookId, chapter, title) values(96, 4, 12, "To Wonder | Zastanawiać się");
insert into chapters (id, bookId, chapter, title) values(97, 4, 13, "Relative Clauses | Zdania Względne");
insert into chapters (id, bookId, chapter, title) values(98, 4, 14, "Purpose Clauses | Zdania Przyczynowo-Skutkowe");
insert into chapters (id, bookId, chapter, title) values(99, 4, 15, "Linking Words (contrast) | Spójniki Kontrastujące");
insert into chapters (id, bookId, chapter, title) values(100, 4, 16, "Giving Reason, Adding Information | Podanie Przyczyny, Dodanie Informacji");
insert into chapters (id, bookId, chapter, title) values(101, 4, 17, "So/Such, So Many, So Much | Tak, Tak Wiele, Tak Dużo");
insert into chapters (id, bookId, chapter, title) values(102, 4, 18, "Past Perfect | Czas Zaprzeszły");
insert into chapters (id, bookId, chapter, title) values(103, 4, 19, "Third Conditional | Trzeci Tryb Warunkowy");
insert into chapters (id, bookId, chapter, title) values(104, 4, 20, "I Wish | Chciałbym, Żałuję, Szkoda że....");
insert into chapters (id, bookId, chapter, title) values(105, 4, 21, "Modal Verbs - Possibility | Czasowniki Modalne - Możliwość/Prawdopodobieństwo");
insert into chapters (id, bookId, chapter, title) values(106, 4, 22, "Modal Verbs in the Past | Czasowniki Modalne w Czasie Przeszłym");
insert into chapters (id, bookId, chapter, title) values(107, 4, 23, "Numbers | Liczby");
insert into chapters (id, bookId, chapter, title) values(108, 4, 24, "Reported Speech 1 | Mowa Zależna, część 1");
insert into chapters (id, bookId, chapter, title) values(109, 4, 25, "Prepositions 4 | Przyimki, część 4");
insert into chapters (id, bookId, chapter, title) values(110, 4, 26, "Expressions 4 | Wyrażenia, część 4");
insert into chapters (id, bookId, chapter, title) values(111, 4, 27, "27 Common Mistakes 1 | Często Popełniane Błędy, część 1");
insert into chapters (id, bookId, chapter, title) values(112, 4, 28, "Review - Sprawdź Się!");
insert into chapters (id, bookId, chapter, title) values(113, 5, 1, "Tenses Review | Powtórka Czasów");
insert into chapters (id, bookId, chapter, title) values(114, 5, 2, "Indirect Questions 2 | Pytania Zależne, część 2");
insert into chapters (id, bookId, chapter, title) values(115, 5, 3, "It Takes 2 | To zabiera/zajmuje, część 2");
insert into chapters (id, bookId, chapter, title) values(116, 5, 4, "Find it | Wyrażanie Opinii");
insert into chapters (id, bookId, chapter, title) values(117, 5, 5, "Gerund & Infinitive 2 | Czasownik z końcówką -ing & Bezokolicznik, część 2");
insert into chapters (id, bookId, chapter, title) values(118, 5, 6, "Bare Infinitive 2 | Nagi Bezokolicznik, część 2");
insert into chapters (id, bookId, chapter, title) values(119, 5, 7, "Modal Verbs - all meanings | Czasowniki Modalne - wszystkie znaczenia");
insert into chapters (id, bookId, chapter, title) values(120, 5, 8, "There in all uses | There we wszystkich użyciach");
insert into chapters (id, bookId, chapter, title) values(121, 5, 9, "So Do I / Neither Do I | Ja Też / Ja Też Nie");
insert into chapters (id, bookId, chapter, title) values(122, 5, 10, "Conditionals - Review | Tryby Warunkowe - Powtórka");
insert into chapters (id, bookId, chapter, title) values(123, 5, 11, "Wish, If only | Chciałbym, Szkoda, że..., Gdybym tylko");
insert into chapters (id, bookId, chapter, title) values(124, 5, 12, "Result & Condition Clauses | Wyrażanie Rezultatu i Warunku");
insert into chapters (id, bookId, chapter, title) values(125, 5, 13, "Linking Words: despite, due to etc. | Spójniki: pomimo, z powodu itd");
insert into chapters (id, bookId, chapter, title) values(126, 5, 14, "Passive Voice 2 | Strona Bierna, część 2");
insert into chapters (id, bookId, chapter, title) values(127, 5, 15, "Reported Speech 2 | Mowa Zależna, część 2");
insert into chapters (id, bookId, chapter, title) values(128, 5, 16, "Like / As | Tak, Jak, Jako");
insert into chapters (id, bookId, chapter, title) values(129, 5, 17, "Questions Tags | Pytanie Rozłączne (prawda? nieprawdaż?)");
insert into chapters (id, bookId, chapter, title) values(130, 5, 18, "As If, As Though; Verb + Adj | Tak Jakby; Czasowniki + przymiotniki");
insert into chapters (id, bookId, chapter, title) values(131, 5, 19, "To be Supposed to do sth | Mieć coś zrobić");
insert into chapters (id, bookId, chapter, title) values(132, 5, 20, "Emphasis: Do, Did; adverbs | Wzmocnienie za pomocą Do/Did lub Przysłówków");
insert into chapters (id, bookId, chapter, title) values(133, 5, 21, "The (More)..., The (More)... | Im ..., Tym ....");
insert into chapters (id, bookId, chapter, title) values(134, 5, 22, "No Matter who/what/when... | Nieważne kto/co/kiedy...");
insert into chapters (id, bookId, chapter, title) values(135, 5, 23, "Whatever, Whichever, Wherever | Cokolwiek, Którykolwiek, Gdziekolwiek");
insert into chapters (id, bookId, chapter, title) values(136, 5, 24, "Cleft Sentences, It Was Me Who... | Zdania typu To Byłem Ja...");
insert into chapters (id, bookId, chapter, title) values(137, 5, 25, "Prepositions 5 | Przyimki, część 5");
insert into chapters (id, bookId, chapter, title) values(138, 5, 26, "Expressions 5 | Wyrażenia, część 5");
insert into chapters (id, bookId, chapter, title) values(139, 5, 27, "Common Mistakes 2 | Często Popełniane Błędy, część 2");
insert into chapters (id, bookId, chapter, title) values(140, 5, 28, "Review | Powtórka");
insert into chapters (id, bookId, chapter, title) values(141, 6, 1, "Articles | Rodzajniki");
insert into chapters (id, bookId, chapter, title) values(142, 6, 2, "Countable & Uncountable Nouns | Rzeczowniki Policzalne i Niepoliczalne");
insert into chapters (id, bookId, chapter, title) values(143, 6, 3, "Gerund & Infinitive 3 | Czasownik z końcówką -ing & Bezokolicznik, część 3");
insert into chapters (id, bookId, chapter, title) values(144, 6, 4, "To + Gerund | ‘To + Czasownik z końcówką -ing’");
insert into chapters (id, bookId, chapter, title) values(145, 6, 5, "As ... As - All Forms | Tak ... Jak - Wszystkie Formy");
insert into chapters (id, bookId, chapter, title) values(146, 6, 6, "Reported Speech 3 | Mowa Zależna, część 3");
insert into chapters (id, bookId, chapter, title) values(147, 6, 7, "Passive Voice 3 | Strona Bierna, część 3");
insert into chapters (id, bookId, chapter, title) values(148, 6, 8, "Have Something Done | Gdy ktoś coś dla nas robi");
insert into chapters (id, bookId, chapter, title) values(149, 6, 9, "Unreal Time | Użycie Czasu Przeszłego z wyrażeniami It’s high time, Wish, I’d rather, etc..");
insert into chapters (id, bookId, chapter, title) values(150, 6, 10, "Future Perfect Tenses | Czasy Przyszłe Dokonane");
insert into chapters (id, bookId, chapter, title) values(151, 6, 11, "Participles | Imiesłowy");
insert into chapters (id, bookId, chapter, title) values(152, 6, 12, "Linking Words | Spójniki");
insert into chapters (id, bookId, chapter, title) values(153, 6, 13, "Reading Numbers | Jak Odczytać Liczby");
insert into chapters (id, bookId, chapter, title) values(154, 6, 14, "Other Grammar Expressions | Inne Wyrażenia Gramatyczne");
insert into chapters (id, bookId, chapter, title) values(155, 6, 15, "Neither, Either, None, Both, All | Żaden, Którykolwiek, Obydwa, Wszystkie itp");
insert into chapters (id, bookId, chapter, title) values(156, 6, 16, "So, Such, Too, Enough | Tak, Tak Dużo, Za Dużo, Wystarczająco");
insert into chapters (id, bookId, chapter, title) values(157, 6, 17, "Happen To & Make It | Określenie Przypadku & Osiągnięcia");
insert into chapters (id, bookId, chapter, title) values(158, 6, 18, "Irregular Verbs | Czasowniki Nieregularne");
insert into chapters (id, bookId, chapter, title) values(159, 6, 19, "Mixed Conditionals | Mieszane Tryby Warunkowe");
insert into chapters (id, bookId, chapter, title) values(160, 6, 20, "The Subjunctive | Tryb Łączący");
insert into chapters (id, bookId, chapter, title) values(161, 6, 21, "Inversion | Inwersj");
insert into chapters (id, bookId, chapter, title) values(162, 6, 22, "With And Without Prepositions | Z oraz Bez Przyimków");
insert into chapters (id, bookId, chapter, title) values(163, 6, 23, "Mix Of Phrases | Różne Zwroty");
insert into chapters (id, bookId, chapter, title) values(164, 6, 24, "Prepositions 6 | Przyimki, część 6");
insert into chapters (id, bookId, chapter, title) values(165, 6, 25, "Expressions 6 | Wyrażenia, część 6");
insert into chapters (id, bookId, chapter, title) values(166, 6, 26, "Sayings | Powiedzenia");
insert into chapters (id, bookId, chapter, title) values(167, 6, 27, "Slang | Angielski Argot");
insert into chapters (id, bookId, chapter, title) values(168, 6, 28, "Review - Sprawdź Się!");
insert into chapters (id, bookId, chapter, title) values(169, 7, 1, "To Turn");
insert into chapters (id, bookId, chapter, title) values(170, 7, 2, "To Look");
insert into chapters (id, bookId, chapter, title) values(171, 7, 3, "To Take & Put – przeciwieństwa");
insert into chapters (id, bookId, chapter, title) values(172, 7, 4, "To Tak");
insert into chapters (id, bookId, chapter, title) values(173, 7, 5, "To Put");
insert into chapters (id, bookId, chapter, title) values(174, 7, 6, "To Come & Go");
insert into chapters (id, bookId, chapter, title) values(175, 7, 7, "To Go");
insert into chapters (id, bookId, chapter, title) values(176, 7, 8, "To Come");
insert into chapters (id, bookId, chapter, title) values(177, 7, 9, "To Break");
insert into chapters (id, bookId, chapter, title) values(178, 7, 10, "To Give");
insert into chapters (id, bookId, chapter, title) values(179, 7, 11, "To Get");
insert into chapters (id, bookId, chapter, title) values(180, 7, 12, "To Get, Work out, Sort out & Find out");
insert into chapters (id, bookId, chapter, title) values(181, 7, 13, "To Throw & To Move");
insert into chapters (id, bookId, chapter, title) values(182, 7, 14, "To Fill, Check & Sign");
insert into chapters (id, bookId, chapter, title) values(183, 7, 15, "Other Useful Phrasal Verbs, part 1");
insert into chapters (id, bookId, chapter, title) values(184, 7, 16, "Review");
insert into chapters (id, bookId, chapter, title) values(185, 8, 1, "To Fall");
insert into chapters (id, bookId, chapter, title) values(186, 8, 2, "To Make");
insert into chapters (id, bookId, chapter, title) values(187, 8, 3, "To Run & Tell");
insert into chapters (id, bookId, chapter, title) values(188, 8, 4, "To Pick & Carry");
insert into chapters (id, bookId, chapter, title) values(189, 8, 5, "To Show & Send");
insert into chapters (id, bookId, chapter, title) values(190, 8, 6, "To Sit & Stand");
insert into chapters (id, bookId, chapter, title) values(191, 8, 7, "To Pass & Drop");
insert into chapters (id, bookId, chapter, title) values(192, 8, 8, "To Hang & Stay");
insert into chapters (id, bookId, chapter, title) values(193, 8, 9, "To Cut & Kick");
insert into chapters (id, bookId, chapter, title) values(194, 8, 10, "To Pay & Hold");
insert into chapters (id, bookId, chapter, title) values(195, 8, 11, "To Think, Catch & Try");
insert into chapters (id, bookId, chapter, title) values(196, 8, 12, "To See, Tear & Talk");
insert into chapters (id, bookId, chapter, title) values(197, 8, 13, "To Let, Grow & Do");
insert into chapters (id, bookId, chapter, title) values(198, 8, 14, "Other Useful Phrasal Verbs, part 2");
insert into chapters (id, bookId, chapter, title) values(199, 8, 15, "Other Useful Phrasal Verbs, part 3");
insert into chapters (id, bookId, chapter, title) values(200, 8, 16, "Review");
insert into chapters (id, bookId, chapter, title) values(201, 9, 1, "To Bring");
insert into chapters (id, bookId, chapter, title) values(202, 9, 2, "To Call");
insert into chapters (id, bookId, chapter, title) values(203, 9, 3, "To Set & Settle");
insert into chapters (id, bookId, chapter, title) values(204, 9, 4, "To Keep & Back");
insert into chapters (id, bookId, chapter, title) values(205, 9, 5, "To Leave & Speak");
insert into chapters (id, bookId, chapter, title) values(206, 9, 6, "To Pull & Knock");
insert into chapters (id, bookId, chapter, title) values(207, 9, 7, "To Blow, Wear & Hand");
insert into chapters (id, bookId, chapter, title) values(208, 9, 8, "To Live & Draw");
insert into chapters (id, bookId, chapter, title) values(209, 9, 9, "To Dig, Roll & Slip");
insert into chapters (id, bookId, chapter, title) values(210, 9, 10, "Other Useful Phrasal Verbs, part 4");
insert into chapters (id, bookId, chapter, title) values(211, 9, 11, "Other Useful Phrasal Verbs, part 5");
insert into chapters (id, bookId, chapter, title) values(212, 9, 12, "Other Useful Phrasal Verbs, part 6");
insert into chapters (id, bookId, chapter, title) values(213, 9, 13, "Other Useful Phrasal Verbs, part 7");
insert into chapters (id, bookId, chapter, title) values(214, 9, 14, "Other Useful Phrasal Verbs, part 8");
insert into chapters (id, bookId, chapter, title) values(215, 9, 15, "Common Informal Phrasal Verbs");
insert into chapters (id, bookId, chapter, title) values(216, 9, 16, "Review");
insert into chapters (id, bookId, chapter, title) values(217, 10, 1, "The Company, czyli Firma");
insert into chapters (id, bookId, chapter, title) values(218, 10, 2, "The Office, czyli Biuro");
insert into chapters (id, bookId, chapter, title) values(219, 10, 3, "My Job & Tasks, czyli Moja Praca i Zadania");
insert into chapters (id, bookId, chapter, title) values(220, 10, 4, "Meetings, czyli Spotkania");
insert into chapters (id, bookId, chapter, title) values(221, 10, 5, "Money & Prices, czyli Pieniądze i Ceny");
insert into chapters (id, bookId, chapter, title) values(222, 10, 6, "Projects & Documents, czyli Projekty i Dokumenty");
insert into chapters (id, bookId, chapter, title) values(223, 10, 7, "Telephone Conversations, czyli Rozmowy Telefoniczne");
insert into chapters (id, bookId, chapter, title) values(224, 10, 8, "Product Description, czyli Opis Produktu");
insert into chapters (id, bookId, chapter, title) values(225, 10, 9, "On a Business Trip, czyli W Podróży Służbowej");
insert into chapters (id, bookId, chapter, title) values(226, 10, 10, "Business Lunch, czyli Obiad Służbowy");
insert into chapters (id, bookId, chapter, title) values(227, 10, 11, "Customers, czyli Klienci");
insert into chapters (id, bookId, chapter, title) values(228, 10, 12, "Computers, czyli Komputery");
insert into chapters (id, bookId, chapter, title) values(229, 10, 13, "Advertising, czyli Reklama");
insert into chapters (id, bookId, chapter, title) values(230, 10, 14, "Business & Investments, czyli Interesy i Inwestycje");
insert into chapters (id, bookId, chapter, title) values(231, 10, 15, "Marketing 1, czyli Marketing, część 1");
insert into chapters (id, bookId, chapter, title) values(232, 10, 16, "Marketing 2, czyli Marketing, część 2");
insert into chapters (id, bookId, chapter, title) values(233, 10, 17, "Banking, czyli Bankowość");
insert into chapters (id, bookId, chapter, title) values(234, 10, 18, "Data, Research & Information, czyli Dane, Badania i Informacje");
insert into chapters (id, bookId, chapter, title) values(235, 10, 19, "Selling & Buying, czyli Kupowanie i Sprzedawanie");
insert into chapters (id, bookId, chapter, title) values(236, 10, 20, "Trouble, czyli Kłopoty");
insert into chapters (id, bookId, chapter, title) values(237, 10, 21, "At Work, czyli W Pracy");
insert into chapters (id, bookId, chapter, title) values(238, 10, 22, "Economy & Government, czyli Gospodarka i Rząd");
insert into chapters (id, bookId, chapter, title) values(239, 10, 23, "Numbers, czyli Liczby");
insert into chapters (id, bookId, chapter, title) values(240, 10, 24, "Organising & Planning, czyli Organizowanie i Planowanie ");
insert into chapters (id, bookId, chapter, title) values(241, 10, 25, "At Reception, czyli W Recepcji");
insert into chapters (id, bookId, chapter, title) values(242, 10, 26, "Time Expressions, czyli Wyrażenia związane z Czasem");
insert into chapters (id, bookId, chapter, title) values(243, 10, 27, "Media");
insert into chapters (id, bookId, chapter, title) values(244, 10, 28, "Location, czyli Lokalizacja");
insert into chapters (id, bookId, chapter, title) values(245, 10, 29, "Human Resources, czyli Zasoby Ludzkie");
insert into chapters (id, bookId, chapter, title) values(246, 10, 30, "Questions, czyli Pytania");
insert into chapters (id, bookId, chapter, title) values(247, 10, 31, "Useful Adjectives, czyli Przydatne Przymiotniki");
insert into chapters (id, bookId, chapter, title) values(248, 10, 32, "E-mails");
insert into chapters (id, bookId, chapter, title) values(249, 10, 33, "Presentations, czyli Prezentacje");
insert into chapters (id, bookId, chapter, title) values(250, 10, 34, "Discussions 1, czyli Dyskusje, część 1");
insert into chapters (id, bookId, chapter, title) values(251, 10, 35, "Discussions 2, czyli Dyskusje, część 2");
insert into chapters (id, bookId, chapter, title) values(252, 11, 1, "The Company, czyli Firma");
insert into chapters (id, bookId, chapter, title) values(253, 11, 2, "The Office & Stationery, czyli Biuro i Materiały Biurowe");
insert into chapters (id, bookId, chapter, title) values(254, 11, 3, "Meetings, czyli Spotkania");
insert into chapters (id, bookId, chapter, title) values(255, 11, 4, "Everyday Tasks, czyli Codzienne Zadania do Wykonania");
insert into chapters (id, bookId, chapter, title) values(256, 11, 5, "Legal Issues, czyli Kwestie Prawne");
insert into chapters (id, bookId, chapter, title) values(257, 11, 6, "Stock Market & Real Estate, Rynek Papierów Wartościowych i Nieruchomości");
insert into chapters (id, bookId, chapter, title) values(258, 11, 7, "Money & Finance, czyli Pieniądze i Finanse");
insert into chapters (id, bookId, chapter, title) values(259, 11, 8, "Products, Brands & Customers, czyli Produkty, Marki i Klienci");
insert into chapters (id, bookId, chapter, title) values(260, 11, 9, "Business, czyli Interesy, Działalność Biznesowa");
insert into chapters (id, bookId, chapter, title) values(261, 11, 10, "Management, czyli Zarządzanie");
insert into chapters (id, bookId, chapter, title) values(262, 11, 11, "IT & Computers, czyli IT i Komputery");
insert into chapters (id, bookId, chapter, title) values(263, 11, 12, "Advertising & Promotion, czyli Reklama i Promocja");
insert into chapters (id, bookId, chapter, title) values(264, 11, 13, "The Market & Marketing, czyli Rynek i Marketing");
insert into chapters (id, bookId, chapter, title) values(265, 11, 14, "Human Resources, czyli Zasoby Ludzkie");
insert into chapters (id, bookId, chapter, title) values(266, 11, 15, "Research, czyli Badania");
insert into chapters (id, bookId, chapter, title) values(267, 11, 16, "Banking, czyli Bankowość");
insert into chapters (id, bookId, chapter, title) values(268, 11, 17, "Negotiations, czyli Negocjacje");
insert into chapters (id, bookId, chapter, title) values(269, 11, 18, "Accounting, czyli Księgowość ");
insert into chapters (id, bookId, chapter, title) values(270, 11, 19, "Project Management, czyli Zarządzanie Projektem");
insert into chapters (id, bookId, chapter, title) values(271, 11, 20, "Economics & the Economy, czyli Ekonomia i Gospodarka");
insert into chapters (id, bookId, chapter, title) values(272, 11, 21, "Production, czyli Produkcja");
insert into chapters (id, bookId, chapter, title) values(273, 11, 22, "Sales, Purchases & Costs, czyli Sprzedaż, Zakupy i Koszty");
insert into chapters (id, bookId, chapter, title) values(274, 11, 23, "Work & Employment, czyli Praca i Zatrudnienie");
insert into chapters (id, bookId, chapter, title) values(275, 11, 24, "Problems at Work, czyli Problemy w Pracy");
insert into chapters (id, bookId, chapter, title) values(276, 11, 25, "Technology & Development, czyli Technologia i Rozwój");
insert into chapters (id, bookId, chapter, title) values(277, 11, 26, "Administrative Tasks, czyli Zadania Administracyjne");
insert into chapters (id, bookId, chapter, title) values(278, 11, 27, "Indicators, czyli Wskaźniki. 110");
insert into chapters (id, bookId, chapter, title) values(279, 11, 28, "Useful Adjectives & Adverbs, czyli Przydatne Przymiotniki i Przysłówki");
insert into chapters (id, bookId, chapter, title) values(280, 11, 29, "Telephone Conversations, czyli Rozmowy Telefoniczne");
insert into chapters (id, bookId, chapter, title) values(281, 11, 30, "E-mail Correspondence, czyli Korespondencja E-mailowa");
insert into chapters (id, bookId, chapter, title) values(282, 11, 31, "Presentations Step by Step, czyli Prezentacje Krok po Kroku");
insert into chapters (id, bookId, chapter, title) values(283, 11, 32, "Expressions, czyli Wyrażenia");
insert into chapters (id, bookId, chapter, title) values(284, 11, 33, "Discussions 1, czyli Dyskusje, część 1");
insert into chapters (id, bookId, chapter, title) values(285, 11, 34, "Discussions 2, czyli Dyskusje, część 2");
insert into chapters (id, bookId, chapter, title) values(286, 11, 35, "Everyday Talk, czyli Codzienne Rozmowy");
insert into chapters (id, bookId, chapter, title) values(287, 12, 1, "Running a Company, czyli Prowadzenie Firmy");
insert into chapters (id, bookId, chapter, title) values(288, 12, 2, "In The Office, czyli W Biurze");
insert into chapters (id, bookId, chapter, title) values(289, 12, 3, "Tasks & Responsibilities, czyli Zadania i Obowiązki");
insert into chapters (id, bookId, chapter, title) values(290, 12, 4, "Conferences & Meetings, czyli Konferencje i Spotkania");
insert into chapters (id, bookId, chapter, title) values(291, 12, 5, "Legal Issues, czyli Kwestie Prawne");
insert into chapters (id, bookId, chapter, title) values(292, 12, 6, "Investments, czyli Inwestycje");
insert into chapters (id, bookId, chapter, title) values(293, 12, 7, "Finance, czyli Finanse");
insert into chapters (id, bookId, chapter, title) values(294, 12, 8, "Product Management, czyli Zarządzanie Produktem");
insert into chapters (id, bookId, chapter, title) values(295, 12, 9, "Management, czyli Zarządzanie");
insert into chapters (id, bookId, chapter, title) values(296, 12, 10, "IT");
insert into chapters (id, bookId, chapter, title) values(297, 12, 11, "Advertising, czyli Reklama");
insert into chapters (id, bookId, chapter, title) values(298, 12, 12, "Brand & Marketing, czyli Marka i Marketing ");
insert into chapters (id, bookId, chapter, title) values(299, 12, 13, "Human Resources, czyli Zasoby Ludzkie");
insert into chapters (id, bookId, chapter, title) values(300, 12, 14, "R&D, Technology, czyli Badania i Rozwój, Technologia");
insert into chapters (id, bookId, chapter, title) values(301, 12, 15, "Project Management, czyli Zarządzanie Projektem");
insert into chapters (id, bookId, chapter, title) values(302, 12, 16, "Negotiating Contracts, czyli Negocjowanie Umów");
insert into chapters (id, bookId, chapter, title) values(303, 12, 17, "Accounting, czyli Księgowość");
insert into chapters (id, bookId, chapter, title) values(304, 12, 18, "Banking & Insurance, czyli Bankowość i Ubezpieczenia");
insert into chapters (id, bookId, chapter, title) values(305, 12, 19, "Economy, czyli Gospodarka");
insert into chapters (id, bookId, chapter, title) values(306, 12, 20, "Production Industry, czyli Przemysł Produkcyjny");
insert into chapters (id, bookId, chapter, title) values(307, 12, 21, "Sales, czyli Sprzedaż");
insert into chapters (id, bookId, chapter, title) values(308, 12, 22, "Purchases & Costs, czyli Zakupy i Koszty");
insert into chapters (id, bookId, chapter, title) values(309, 12, 23, "Problem Solving, czyli Rozwiązywanie Problemów");
insert into chapters (id, bookId, chapter, title) values(310, 12, 24, "Logistics, czyli Logistyka");
insert into chapters (id, bookId, chapter, title) values(311, 12, 25, "Labour & Customer Relations, czyli Stosunki Pracy i Relacje z Klientami");
insert into chapters (id, bookId, chapter, title) values(312, 12, 26, "Administration & Contracts, czyli Administracja i Umowy");
insert into chapters (id, bookId, chapter, title) values(313, 12, 27, "Trends & Indicators, czyli Tendencje i Wskaźniki");
insert into chapters (id, bookId, chapter, title) values(314, 12, 28, "Useful Adjectives, czyli Przydatne Przymiotniki");
insert into chapters (id, bookId, chapter, title) values(315, 12, 29, "E-mail & Phone Contact, czyli Kontakt Mailowy i Telefoniczny");
insert into chapters (id, bookId, chapter, title) values(316, 12, 30, "Useful Phrasal Verbs, czyli Przydatne Czasowniki Złożone");
insert into chapters (id, bookId, chapter, title) values(317, 12, 31, "Business Idioms, czyli Biznesowe Wyrażenia Idiomatyczne ");
insert into chapters (id, bookId, chapter, title) values(318, 12, 32, "In a Meeting, czyli Na Spotkaniu");
insert into chapters (id, bookId, chapter, title) values(319, 12, 33, "Discussions, czyli Dyskusje");
insert into chapters (id, bookId, chapter, title) values(320, 12, 34, "Everyday Talk 1, czyli Codzienne Rozmowy, część 1");
insert into chapters (id, bookId, chapter, title) values(321, 12, 35, "Everyday Talk 2, czyli Codzienne Rozmowy, część 2");